/// Tableau d'aide au choix d'une table article (Opale Électricité).
///
/// FICHIER GÉNÉRÉ par tools/generer_influences.py depuis
/// docs/modules/03_donnees_reference.md : ne pas modifier à la main.
library;

import 'choix_table_article_modele.dart';

const List<LigneChoixTable> choixTableArticle = [
  LigneChoixTable('TT', 'BAES', 'Non', 'Non', 'Non', 'Non', 'Non', 'Oui', 'Non', 1),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Non', 'Non', 'Non', 'Oui', 'Non', 2),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Sans DRPE', 'Non', 'Non', 'Oui', 'Non', 3),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'Non', 'Oui', 'Non', 4),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'Non', 'Oui', 'Non', 5),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Non', 'Oui', 'Non', 'Oui', 'Non', 6),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Non', 'Non', 'Non', 'Oui', 'Non', 7),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Non', 'Non', 'Non', 'Non', 'Oui', 'Non', 8),
  LigneChoixTable('TT', 'BAES', 'Non', 'Non', 'Non', 'Oui', 'Non', 'Oui', 'Non', 9),
  LigneChoixTable('TT', 'BAES', 'Non', 'Non', 'Non', 'Non', 'ERP 5', 'Oui', 'Non', 10),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Non', 'Non', 'ERP 5', 'Oui', 'Non', 11),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Non', 'Oui', 'ERP 5', 'Oui', 'Non', 12),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Sans DRPE', 'Oui', 'ERP 5', 'Oui', 'Non', 13),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Sans DRPE', 'Non', 'ERP 5', 'Oui', 'Non', 14),
  LigneChoixTable('TT', 'BAES', 'Non', 'Non', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 15),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Non', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 16),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 17),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 18),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 19),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 20),
  LigneChoixTable('TT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 21),
  LigneChoixTable('TT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 22),
  LigneChoixTable('TT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 23),
  LigneChoixTable('TT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 24),
  LigneChoixTable('TT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 25),
  LigneChoixTable('TT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 26),
  LigneChoixTable('TT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 27),
  LigneChoixTable('TT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 28),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Non', 'Non', 'Non', 'Non', 'Oui', 'NF C 13-100', 29),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Non', 'Non', 'Non', 'Oui', 'NF C 13-100', 30),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'Non', 'Oui', 'NF C 13-100', 31),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'Non', 'Oui', 'NF C 13-100', 32),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Non', 'Oui', 'Non', 'Oui', 'NF C 13-100', 33),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Non', 'Non', 'Oui', 'Non', 'Oui', 'NF C 13-100', 34),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 35),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 36),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 37),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 38),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 39),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 40),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 41),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 42),
  LigneChoixTable('TT', 'BAES', 'Non', 'Non', 'Non', 'Non', 'Non', 'Non', 'Non', 43),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Non', 'Non', 'Non', 'Non', 'Non', 44),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Sans DRPE', 'Non', 'Non', 'Non', 'Non', 45),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'Non', 'Non', 'Non', 46),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'Non', 'Non', 'Non', 47),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Non', 'Oui', 'Non', 'Non', 'Non', 48),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Non', 'Non', 'Non', 'Non', 'Non', 49),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Non', 'Non', 'Non', 'Non', 'Non', 'Non', 50),
  LigneChoixTable('TT', 'BAES', 'Non', 'Non', 'Non', 'Oui', 'Non', 'Non', 'Non', 51),
  LigneChoixTable('TT', 'BAES', 'Non', 'Non', 'Non', 'Non', 'ERP 5', 'Non', 'Non', 52),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Non', 'Non', 'ERP 5', 'Non', 'Non', 53),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Non', 'Oui', 'ERP 5', 'Non', 'Non', 54),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Sans DRPE', 'Oui', 'ERP 5', 'Non', 'Non', 55),
  LigneChoixTable('TT', 'BAES', 'Non', 'Oui', 'Sans DRPE', 'Non', 'ERP 5', 'Non', 'Non', 56),
  LigneChoixTable('TT', 'BAES', 'Non', 'Non', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'Non', 57),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Non', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'Non', 58),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'Non', 59),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 60),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 61),
  LigneChoixTable('TT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'Non', 62),
  LigneChoixTable('TT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'Non', 63),
  LigneChoixTable('TT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'Non', 64),
  LigneChoixTable('TT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 65),
  LigneChoixTable('TT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 66),
  LigneChoixTable('TT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'Non', 67),
  LigneChoixTable('TT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'Non', 68),
  LigneChoixTable('TT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 69),
  LigneChoixTable('TT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 70),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Non', 'Non', 'Non', 'Non', 'Non', 'NF C 13-100', 71),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Non', 'Non', 'Non', 'Non', 'NF C 13-100', 72),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'Non', 'Non', 'NF C 13-100', 73),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'Non', 'Non', 'NF C 13-100', 74),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Non', 'Oui', 'Non', 'Non', 'NF C 13-100', 75),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Non', 'Non', 'Oui', 'Non', 'Non', 'NF C 13-100', 76),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-100', 77),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-100', 78),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-100', 79),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-100', 80),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-100', 81),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-100', 82),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-100', 83),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-100', 84),
  LigneChoixTable('TT', 'BAES', 'Non', 'Non', 'Non', 'Non', 'ERP 1 dans CC', 'Oui', 'Non', 85),
  LigneChoixTable('TT', 'BAES', 'Non', 'Non', 'Non', 'Non', 'ERP 1 dans CC', 'Non', 'Non', 86),
  LigneChoixTable('TT', 'BAES + BAEH', 'Non', 'Non', 'Non', 'Oui', 'ERP 5', 'Oui', 'Non', 87),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Non', 'Non', 'Oui', 'ERP 5', 'Oui', 'Non', 88),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 5', 'Oui', 'Non', 89),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 5', 'Oui', 'Non', 90),
  LigneChoixTable('TT', 'BAES + BAEH', 'Non', 'Oui', 'Sans DRPE', 'Oui', 'ERP 5', 'Oui', 'Non', 91),
  LigneChoixTable('TT', 'BAES + BAEH', 'Non', 'Oui', 'Non', 'Oui', 'ERP 5', 'Oui', 'Non', 92),
  LigneChoixTable('TT', 'BAES + BAEH', 'Non', 'Non', 'Non', 'Oui', 'ERP 5', 'Non', 'Non', 93),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Non', 'Non', 'Oui', 'ERP 5', 'Non', 'Non', 94),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 5', 'Non', 'Non', 95),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 5', 'Non', 'Non', 96),
  LigneChoixTable('TT', 'BAES + BAEH', 'Non', 'Oui', 'Sans DRPE', 'Oui', 'ERP 5', 'Non', 'Non', 97),
  LigneChoixTable('TT', 'BAES + BAEH', 'Non', 'Oui', 'Non', 'Oui', 'ERP 5', 'Non', 'Non', 98),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Non', 'Non', 'Non', 'Non', 'Oui', 'NF C 13-200', 99),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Non', 'Non', 'Non', 'Oui', 'NF C 13-200', 100),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'Non', 'Oui', 'NF C 13-200', 101),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'Non', 'Oui', 'NF C 13-200', 102),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Non', 'Oui', 'Non', 'Oui', 'NF C 13-200', 103),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Non', 'Non', 'Oui', 'Non', 'Oui', 'NF C 13-200', 104),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 105),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 106),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 107),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 108),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 109),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 110),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 111),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 112),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Non', 'Non', 'Non', 'Non', 'Non', 'NF C 13-200', 113),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Non', 'Non', 'Non', 'Non', 'NF C 13-200', 114),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'Non', 'Non', 'NF C 13-200', 115),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'Non', 'Non', 'NF C 13-200', 116),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Oui', 'Non', 'Oui', 'Non', 'Non', 'NF C 13-200', 117),
  LigneChoixTable('TN / IT', 'BAES', 'Oui', 'Non', 'Non', 'Oui', 'Non', 'Non', 'NF C 13-200', 118),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-200', 119),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-200', 120),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-200', 121),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-200', 122),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-200', 123),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-200', 124),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-200', 125),
  LigneChoixTable('TN / IT', 'Source Centrale', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-200', 126),
  LigneChoixTable('TT', 'BAES + BAEH', 'Non', 'Non', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 15),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Non', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 16),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 17),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 18),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 19),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 20),
  LigneChoixTable('TT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 21),
  LigneChoixTable('TT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 22),
  LigneChoixTable('TT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 23),
  LigneChoixTable('TT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 24),
  LigneChoixTable('TT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 25),
  LigneChoixTable('TT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'Non', 26),
  LigneChoixTable('TT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 27),
  LigneChoixTable('TT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'Non', 28),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 35),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 36),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 37),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 38),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 39),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 40),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 41),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-100', 42),
  LigneChoixTable('TT', 'BAES + BAEH', 'Non', 'Non', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'Non', 57),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Non', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'Non', 58),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'Non', 59),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 60),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 61),
  LigneChoixTable('TT', 'BAES + BAEH', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'Non', 62),
  LigneChoixTable('TT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'Non', 63),
  LigneChoixTable('TT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'Non', 64),
  LigneChoixTable('TT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 65),
  LigneChoixTable('TT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 66),
  LigneChoixTable('TT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'Non', 67),
  LigneChoixTable('TT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'Non', 68),
  LigneChoixTable('TT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 69),
  LigneChoixTable('TT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'Non', 70),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-100', 77),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-100', 78),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-100', 79),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-100', 80),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-100', 81),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-100', 82),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-100', 83),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-100', 84),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 105),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 106),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 107),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 108),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 109),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 110),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 111),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Oui', 'NF C 13-200', 112),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-200', 119),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-200', 120),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-200', 121),
  LigneChoixTable('TN / IT', 'BAES + Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-200', 122),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-200', 123),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Non', 'ERP 1 à 4', 'Non', 'NF C 13-200', 124),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Sans DRPE', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-200', 125),
  LigneChoixTable('TN / IT', 'Source Centrale (6h)', 'Oui', 'Oui', 'Non', 'Oui', 'ERP 1 à 4', 'Non', 'NF C 13-200', 126),
];
