/// Influences externes : seuils par type de câble et de conduit.
///
/// FICHIER GÉNÉRÉ par tools/generer_influences.py depuis
/// docs/modules/03_donnees_reference.md : ne pas modifier à la main.
library;

import 'influences.dart';

const List<TypeInfluence> typesCables = [
  TypeInfluence(
    nom: 'U1000R2V',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(max: 8),
      'AD': RegleInfluence(max: 7),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 3),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 3),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 3),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 1),
    },
  ),
  TypeInfluence(
    nom: 'U1000RVFV',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(max: 8),
      'AD': RegleInfluence(max: 7),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 4),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 2),
      'AL': RegleInfluence(max: 2),
      'BB': RegleInfluence(max: 2),
      'BC': RegleInfluence(max: 3),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 3),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 1),
    },
    notes: [
      NoteInfluence('Toléré si revétements métalliques reliés à la terre (BC)', []),
    ],
  ),
  TypeInfluence(
    nom: 'H07BN4F',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(max: 8),
      'AD': RegleInfluence(max: 7),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 4),
      'AH': RegleInfluence(max: 3),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 3),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 3),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(exclus: {2}),
    },
  ),
  TypeInfluence(
    nom: 'H07RNF',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(min: 3, max: 5),
      'AD': RegleInfluence(max: 7),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 4),
      'AH': RegleInfluence(max: 3),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 3),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 3),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(exclus: {2}),
    },
    notes: [
      NoteInfluence('Toléré si immersion limitée à 2 mois par an (AD)', [ConditionNiveau('AD', '=', 7)]),
    ],
  ),
  TypeInfluence(
    nom: 'H07RN8F',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(max: 8),
      'AD': RegleInfluence(max: 8),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 4),
      'AH': RegleInfluence(max: 3),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 3),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 3),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(exclus: {2}),
    },
    notes: [
      NoteInfluence('Toléré si absence d\'effort mécanique (AA)', [ConditionNiveau('AA', '<', 4)]),
      NoteInfluence('Toléré si absence d\'effort mécanique (AA)', [ConditionNiveau('AA', '>', 6)]),
    ],
  ),
  TypeInfluence(
    nom: 'H05RNF',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(min: 3, max: 5),
      'AD': RegleInfluence(max: 5),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 3),
      'AH': RegleInfluence(max: 2),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 1),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 1),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(exclus: {2}),
    },
    notes: [
      NoteInfluence('Toléré si tension nominale d\'alimentation par rapport à la terre au plus égale à 250 V (BC)', [ConditionNiveau('BC', '=', 4)]),
    ],
  ),
  TypeInfluence(
    nom: 'H05VVF',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(max: 8),
      'AD': RegleInfluence(max: 6),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 2),
      'AH': RegleInfluence(max: 3),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 3),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 2),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 1),
    },
    notes: [
      NoteInfluence('Toléré si absence d\'effort mécanique (AA)', []),
    ],
  ),
  TypeInfluence(
    nom: 'CR1',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(max: 8),
      'AD': RegleInfluence(max: 7),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 3),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 3),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 3),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 2),
    },
    notes: [
      NoteInfluence('Si AN>2 voir doc. fabr.', []),
    ],
  ),
];

const List<TypeInfluence> typesConduits = [
  TypeInfluence(
    nom: 'MRL',
    usageCourant: false,
    contraintesFixes: ['BC'],
    regles: {
      'AA': RegleInfluence(max: 6),
      'AD': RegleInfluence(max: 2),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 1),
      'AG': RegleInfluence(max: 4),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 2),
      'AL': RegleInfluence(max: 2),
      'BB': RegleInfluence(max: 1),
      'BC': RegleInfluence.toujours(),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 3),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 1),
    },
    notes: [
      NoteInfluence('Voir doc. constructeur si dérogation particulière', []),
    ],
  ),
  TypeInfluence(
    nom: 'CSA',
    usageCourant: false,
    contraintesFixes: ['BC'],
    regles: {
      'AA': RegleInfluence(min: 4, max: 6),
      'AD': RegleInfluence(max: 2),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 3),
      'AH': RegleInfluence(max: 3),
      'AK': RegleInfluence(max: 2),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 1),
      'BC': RegleInfluence.toujours(),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 3),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(exclus: {2}),
    },
    notes: [
      NoteInfluence('Voir doc. constructeur si dérogation particulière', []),
    ],
  ),
  TypeInfluence(
    nom: 'ICTL',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(min: 4, max: 6),
      'AD': RegleInfluence(max: 6),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 3),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 3),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 2),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 1),
    },
  ),
  TypeInfluence(
    nom: 'ICA',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(min: 4, max: 6),
      'AD': RegleInfluence(max: 6),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 2),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 3),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 2),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 1),
    },
  ),
  TypeInfluence(
    nom: 'IRL',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(min: 4, max: 6),
      'AD': RegleInfluence(max: 6),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 2),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 3),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 2),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 1),
    },
  ),
  TypeInfluence(
    nom: 'ICTA',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(min: 4, max: 6),
      'AD': RegleInfluence(max: 6),
      'AE': RegleInfluence(max: 4),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 3),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 3),
      'BC': RegleInfluence(max: 4),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 2),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 1),
    },
  ),
  TypeInfluence(
    nom: 'Goulottes',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(min: 4, max: 6),
      'AD': RegleInfluence(max: 1),
      'AE': RegleInfluence(max: 1),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 1),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 2),
      'BC': RegleInfluence(max: 3),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 2),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 1),
    },
  ),
  TypeInfluence(
    nom: 'Systemes Goulottes',
    usageCourant: true,
    regles: {
      'AA': RegleInfluence(min: 4, max: 6),
      'AD': RegleInfluence(max: 1),
      'AE': RegleInfluence(max: 3),
      'AF': RegleInfluence(max: 3),
      'AG': RegleInfluence(max: 2),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 2),
      'BC': RegleInfluence(max: 3),
      'BD': RegleInfluence(max: 4),
      'BE': RegleInfluence(max: 2),
      'CA': RegleInfluence(max: 2),
      'CB': RegleInfluence(max: 1),
    },
  ),
  TypeInfluence(
    nom: 'Moulures Bois',
    usageCourant: false,
    contraintesFixes: ['BC'],
    regles: {
      'AA': RegleInfluence(min: 4, max: 6),
      'AD': RegleInfluence(max: 1),
      'AE': RegleInfluence(max: 3),
      'AF': RegleInfluence(max: 1),
      'AG': RegleInfluence(max: 1),
      'AH': RegleInfluence(max: 1),
      'AK': RegleInfluence(max: 1),
      'AL': RegleInfluence(max: 1),
      'BB': RegleInfluence(max: 1),
      'BC': RegleInfluence.toujours(),
      'BD': RegleInfluence(max: 1),
      'BE': RegleInfluence(max: 1),
      'CA': RegleInfluence(max: 1),
      'CB': RegleInfluence(max: 1),
    },
  ),
];
